GET http://localhost:3003/api/blogs/

### 
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "Some good stuff",
    "author": "Bob Smith",
    "url": "www.codingcool.io",
    "likes": 1
}

###
DELETE http://localhost:3003/api/blogs/