GET http://localhost:3003/api/blogs/

### 
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "Some good stuff",
    "author": "Bob Smith",
    "url": "www.codingcool.io"
}

###
PUT http://localhost:3003/api/blogs/61200bd6a4dfa240d4677eaa
Content-Type: application/json

{
    "title": "Some good stuff",
    "author": "Bob Smith",
    "url": "www.codingcool.io",
    "likes": 17
}
###
DELETE http://localhost:3003/api/blogs/61200b2edcbb2a2d7008f9ba